# Generated by Django 5.2.5 on 2025-09-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcategory_post_post_slug_postseries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.postseries', verbose_name='series'),
        ),
    ]
