# Generated by Django 5.2.5 on 2025-09-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_post_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='card_img',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
