# Generated by Django 5.2.5 on 2025-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcategory_card_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='card_img',
            field=models.SlugField(default=1, max_length=300),
        ),
    ]
