# Generated by Django 5.2.5 on 2025-09-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postcategory_card_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postseries',
            old_name='tutorial_series',
            new_name='post_series',
        ),
    ]
