# Generated by Django 5.2.5 on 2025-09-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_tutorial_series_postseries_post_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postseries',
            old_name='tutorial_category',
            new_name='post_category',
        ),
    ]
