# Generated by Django 5.2.5 on 2025-09-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_tutorial_category_postseries_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postseries',
            name='post_slug',
            field=models.SlugField(default=1, max_length=200),
        ),
    ]
